name: Deployment - Reusable Workflow

on:
  workflow_call:
    inputs:
      mongodb-uri:
        required: true
        type: string
      kubectl-version:
        description: Provide the Required kubectl Version
        default: v1.26.0
        required: false
        type: string
      k8s-manifest-dir:
        description: Provide the Kubernetes Manifest Directory
        default: kubernetes/
        required: true
        type: string
      environment:
        description: Provide the Environment Name for Deployment
        default: dev
        required: true
        type: string
    outputs:
      application-url:
        value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}
    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true

jobs:
  reuse-deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}

    outputs:
      APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl cli
        uses: azure/setup-kubectl@v4
        with:
          version: ${{ inputs.kubectl-version }}

      - name: Set Kubeconfig
        uses: azure/k8s-set-context@v5
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.k8s-kubeconfig }}

      - name: Fetch Kubernetes Cluster Details
        run: |
          kubectl version --short
          echo ---------------------------------------------
          kubectl get nodes

      # - name: Save NGINX Ingress Controller IP as Github Environment Variable
      #   run: |
      #     echo "INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Save NGINX Ingress Controller IP as Github Environment Variable
        run: |
          SERVER_URL=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
          EXTRACTED_IP=$(echo $SERVER_URL | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
          echo "INGRESS_IP=$EXTRACTED_IP" >> $GITHUB_ENV

      - name: Replace Tokens in Kubernetes Manifests
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "${"
          tokenSuffix: "}"
          files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Check Files
        run: |
          cat ${{ inputs.k8s-manifest-dir }}*.yaml

      # Ensure Namespace Exists (not in instructor manual)
      - name: Ensure Namespace Exists
        run: |
          kubectl create namespace ${{ vars.NAMESPACE }} \
          --dry-run=client \
          -o yaml | kubectl apply -f -

      - name: Create MongoDB Secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ inputs.mongodb-uri }} \
            --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -

      - name: Deploy to Development Environment
        run: |
          kubectl apply -f ${{ inputs.k8s-manifest-dir }}

      - name: Set APP Ingress HOST URL
        id: set-ingress-host-address
        run: |
          echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath='{.items[0].spec.rules[0].host}')" >> $GITHUB_OUTPUT
